apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2024-11-02T18:47:20Z"
  labels:
    kops.k8s.io/cluster: oxn.dev.com
  name: control-plane-europe-west1-b
spec:
  image: ubuntu-os-cloud/ubuntu-2204-jammy-v20240607
  machineType: e2-medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - europe-west1
  zones:
  - europe-west1-b
